### ISSUE TITLE
Flashlight doesn't follow camera position

### ISSUE THREAD

**Issue by WolfeStrider** [Xenthio/RTXFixes#7]
If you crouch your flashlight doesn't follow your camera position so when your in low vents you aren't able to illuminate them which makes it so your unable to see. This is also an issue for larger and smaller playermodels because then the flashlight will be too high or low for it to be useful to you. Also the flashlight height is too high with the normal sized playermodel in comparison to default Garry's Mod projected texture flashlight is coming from somewhere closer to chest height.

https://www.youtube.com/watch?v=o7IpLycB7Ps

**Comment by Xenthio** [comment]
fixed!
